server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: jdbc:h2:mem:restaurantdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    #url: jdbc:mysql://localhost:3306/restaurantdb
    #username: root
    #password: K0fDc2WQNUtPERn
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect